spring:
  application:
    name: manager-app
  datasource:
    url: jdbc:postgresql://localhost:5433/manager
    username: manager
    password: manager
  flyway:
    enabled: true
    baseline-on-migrate: true
    schemas:
      - public
      - user_management
  jpa:
    show-sql: true
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/product-manager
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: manager-app
            client-secret: 7sCvYrQKN2FAbEsEwuPe4ouXQotYqtbs
            scope:
              - openid
              - view_catalogue
              - edit_catalogue
              - microprofile-jwt

server:
  port: 8080

product-list:
  services:
    catalog-service:
      uri: http://localhost:8081
      registration-id: keycloak
